# Generated by Django 3.2.5 on 2021-07-30 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronin_address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('manager_fee', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_claim_amount', models.FloatField(default=0)),
                ('last_claim_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ronin_slp', models.IntegerField(default=0)),
                ('slp_success', models.BooleanField(blank=True, null=True)),
                ('mmr', models.DateTimeField(blank=True, null=True)),
                ('total_matches', models.IntegerField(default=0)),
                ('ign', models.CharField(max_length=200)),
                ('game_stats_success', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
