# Generated by Django 3.2.5 on 2021-07-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholar',
            old_name='manager_fee',
            new_name='manager_share',
        ),
        migrations.AddField(
            model_name='scholar',
            name='scholar_share',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
