# Generated by Django 3.2.5 on 2021-07-30 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210730_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_claim_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
