# Generated by Django 3.2.5 on 2021-07-30 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210730_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
