# Generated by Django 3.2.5 on 2021-07-30 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_scholar_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 18, 27, 41, 373581)),
        ),
    ]
