# Generated by Django 3.2.5 on 2021-07-30 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_scholar_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='in_game_slp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholar',
            name='total_slp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 19, 2, 43, 565546)),
        ),
    ]
