# Generated by Django 3.2.5 on 2021-07-30 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210730_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exchange', models.FloatField(default=0)),
                ('last_update', models.DateField(default=datetime.datetime(2021, 7, 30, 21, 12, 31, 364250))),
            ],
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 21, 12, 31, 364250)),
        ),
    ]
