# Generated by Django 3.2.5 on 2021-07-30 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210730_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='exchange',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='name',
            new_name='symbol',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 21, 13, 29, 485925)),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 30, 21, 13, 29, 484928)),
        ),
    ]
