# Generated by Django 3.2.5 on 2021-07-30 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210730_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 0, 10, 56, 39353)),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 0, 10, 56, 38357)),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronin_address', models.CharField(max_length=200)),
                ('manager_fee', models.FloatField(default=0)),
                ('scholar_fee', models.FloatField(blank=True, default=0, null=True)),
                ('total_fee', models.FloatField(blank=True, default=0, null=True)),
                ('manager_slp', models.FloatField(default=0)),
                ('scholar_slp', models.FloatField(blank=True, default=0, null=True)),
                ('total_slp', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(default=0)),
                ('gas_fee', models.FloatField(default=0)),
                ('last_update', models.DateField(default=datetime.datetime(2021, 7, 31, 0, 10, 56, 39353))),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scholar')),
            ],
        ),
    ]
