# Generated by Django 3.2.5 on 2021-07-30 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210731_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
