# Generated by Django 3.2.5 on 2021-09-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_scholar_last_claim_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
